### PR TITLE
Travisify

### LINKED ISSUE #11: Continuous Delivery
I am thinking the DX might be improved by using Travis to keep the gh-pages branch and the master branch in sync. I'm open to alternatives to Travis as well, it's just the one I'm most familiar with for open source projects. I'll leave this issue up for a few days in case this initiative rankles people and a fiery war of words erupts over which CI/CD system is the best, the merits of human error vs robot error, whether we should be resisting giving away system administrator jobs to soulless machines who will destroy or economy... basically to see if anyone reads this.

### PR DESCRIPTION
**Pull request by billiegoose**
Would fix #11. I will not merge this until all 3 members of the `jus` org have reviewed this pull request.

## Purpose
The net effect of merging this pull request would be that all future changes to the master branch will trigger a Travis script to update the website [jus.js.org](http://jus.js.org)

## Implementation
I added a devDependency on [gh-pages-travis](https://www.npmjs.com/package/gh-pages-travis) which has nice setup instructions.
You can see what the tool looks like when it runs here: [Travis build log](https://travis-ci.org/wmhilton-contrib/jus.js.org/builds/207779862#L439)
You can see what the commits in my 'gh-pages' branch looks like: [here](https://github.com/wmhilton-contrib/jus.js.org/commits/gh-pages)
You can see the resulting Github Pages site: [here](https://wmhilton-contrib.github.io/jus.js.org/)

The thing is controlled by some environment variables that are set in `.travis.yml`:

```
  - DEPLOY_BRANCH="master"
  - SOURCE_DIR="dist"
  - TARGET_BRANCH="gh-pages"
  - SSH_KEY="id_rsa"
  - GIT_NAME="gh-pages-travis"
  - GIT_EMAIL="deploy@travis-ci.org"
```

which translates to, "After running the build step, If the current branch is 'master', push the files in 'dist' into branch 'gh-pages'" The variables GIT_NAME and GIT_EMAIL can be dummy values. They are just what appears as the author on the commit. SSH_KEY is the filename of the git SSH deployment key, which is checked into the repo but in an encrypted form.

I've set up Travis for *this* repo [here](https://travis-ci.org/jus/jus.js.org), created an SSH deployment key [here](https://github.com/jus/jus.js.org/settings/keys) that has write access to *this* repo, and that SSH key is encrypted [here](https://github.com/jus/jus.js.org/blob/9d8336ef8502ffa0e9f5d3e1c142a326171dde93/id_rsa.enc) using the environment variables listed but not revealed [here](https://travis-ci.org/jus/jus.js.org/settings).

Whew!

### CODE REVIEW

**Comment by jdormit** [comment]
This is cool! I'm comfortable with it - as long we keep using PRs to push major changes, this will just simplify the work flow.

**Review by zeke — APPROVED** [review]
Looks great. Thanks for writing up the details on how it all works.

:shipit:

**Comment by wmhilton** [comment]
@jdormit Absolutely we shall use pull requests! I think the only exceptions would be for time-critical hotfixes, like if something went really really wrong and had to be fixed ASAP. But I'm having trouble coming up with even a hypothetical scenario like that.

Even in those situations, you can create a pull request, like "PANIC! TYPO WILL GET US BANNED FROM INTERNET" and then merge it yourself, and it's not really more work than a regular merge. OK, so if for some reason you have git cli push but not a working browser to compose a pull request... See, you have to really contort your mind to come up with a scenario where changing master w/o a pull request makes sense.

**Comment by billiegoose** [comment]
And we have liftoff: https://travis-ci.org/jus/jus.js.org/builds/207994978

**Comment by jdormit** [comment]
Awesome!

**Comment by zeke** [comment]
This is awesome! I feel like Jus should have a twitter so we can celebrate stuff like this. Anyone else feeling that?

**Comment by jdormit** [comment]
That would be sweet! Would it be set up under your email address, or how would that work?

**Comment by zeke** [comment]
> Would it be set up under your email address, or how would that work?

Great question. Open to ideas on how to easily create an email address that can be shared by members of this org. 🤔

**Comment by jdormit** [comment]
This looks promising: https://www.google.com/amp/s/techcrunch.com/2015/02/17/share-twitter-account/amp/

**Pull request merged**
