### PR TITLE
point to the new repo URL

### PR DESCRIPTION
**Pull request by zeke**
github.com/zeke → github.com/jus

### CODE REVIEW

**Comment by jdormit** [comment]
Looks like the travis-ci build isn't set up for the org yet, sohttps://travis-ci.org/jus/jus doesn't point to anything at the moment.

**Comment by zeke** [comment]
Okay I gave Travis permission to the org and synced. Should be good now.

screen shot 2017-02-15 at 2 23 20 pm

**Comment by jdormit** [comment]
Sweet thanks!

**Comment by zeke** [comment]
Deployed! It's a GitHub Pages site, so org member should be able to `npm run deploy` to ship the latest.

**Pull request merged**
